### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by critzo** [throneless-tech/murakami-viz#93]
Attempting to test adding more device data today, I see a 502 Bad Gateway Error when attempting to load the site.

**Comment by critzo** [comment]
Noting that @jheretic identified this as a stalled or shutdown container, and was investigating the cause.

**Comment by jheretic** [comment]
I suspect it might have been a memory issue on the VM, and the OOM killer got it. Memory usage seems stable so far, so we're not likely to get more info unless it happens again. I'm going to suggest modifying the default docker-compose setup so that containers auto-restart on failure, and look into the possibility of adding prometheus metrics if that's easy to do. Does that sound good @critzo?

**Comment by critzo** [comment]
That sounds good to me, yes.

**Comment by rudietuesdays** [comment]
@jheretic @critzo would it be helpful to open a new issue for the modification and close this out?

**Comment by critzo** [comment]
Yes @rudietuesdays Let's open a new issue for the OOM issue. Thanks.

**Comment by rudietuesdays** [comment]
Sounds good, closing this one out!
